import  'bootstrap/dist/css/bootstrap.min.css'
import Layout from "@/comps/Layout";

export const metadata = {
  title: "Blog Test App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
      <body >
        <Layout >
          {children}  
        </Layout>
       
      </body>
    </html>
  );
}
