import  'bootstrap/dist/css/bootstrap.min.css'
import Layout from "@/comps/Layout";
import { AuthProvider } from '@/context/AuthContext';
import { CartProvider } from '@/context/CartContext';



export const metadata = {
  title: "Blog Test App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
      <body >
       
        <AuthProvider>
          <CartProvider>
            <Layout>
              {children}
            </Layout>
          </CartProvider>
        </AuthProvider>
       
      </body>
    </html>
  );
}
